name: CI Pipeline

on: [push]

jobs:
  build-spring-boot-https:
    name: Spring Boot HTTPS - Compile and test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Compile and test
        run: |
          cd spring-boot-https
          chmod +x gradlew
          ./gradlew clean build
  build-cloud-config:
    name: Spring Cloud Config - Compile and test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Compile and test config-server
        run: |
          cd spring-cloud-config/config-server
          chmod +x gradlew
          ./gradlew build
      - name: Compile and test greeting-service
        run: |
          cd spring-cloud-config/greeting-service
          chmod +x gradlew
          ./gradlew build
