name: Spring CI

on: [push]

jobs:
  build:
    name: Spring
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.7
          java-package: jdk
          architecture: x64
      - name: Build spring-boot-https
        run: |
          cd spring-boot-https
          chmod +x gradlew
          ./gradlew build
      - name: Build spring-cloud-config/config-server
        run: |
          cd spring-cloud-config/config-server
          chmod +x gradlew
          ./gradlew build
      - name: spring-cloud-config/greeting-service
        run: |
          cd spring-cloud-config/greeting-service
          chmod +x gradlew
          ./gradlew build
